### ISSUE TITLE
[ENHANCEMENT] Runestone grading support

### ISSUE THREAD

**Issue by ezrichards** [CSCI128/101GradingScript#56]
## Description
We need Runestone autograding + export to Canvas support.

### Issue
Attached is an example (with some info redacted) of a Runestone grade book exported as a CSV. On the admin end of Runestone, we could also export by assignment if that's easier on this end of things.

## Acceptance Criteria 
- [ ] Grades can be transferred from Runestone

[mines_csstem_Gradebook-1686351703163.csv](https://github.com/CSCI128/101GradingScript/files/11710565/mines_csstem_Gradebook-1686351703163.csv)

**Comment by TriHardStudios** [comment]
<img width="1302" alt="image" src="https://github.com/CSCI128/101GradingScript/assets/26157342/2267027f-1240-4147-8bbb-4b50357606fe">
Need to investigate single assignment export rather than full export

**Comment by ezrichards** [comment]
Right, so I just tried this. Apparently it only filters on the visual side of things on the site, and doesn't modify the exported csv..which just looks like the aforementioned one anyways.

Is this detrimental to the grading system? We could (albeit rather tediously) clean the .csv of all assignments other than the current one being graded.

**Comment by TriHardStudios** [comment]
It will be fine i think -  we will just need another menu to select which week we are actively grading.

From there it will be easy peasy as Pandas allows very easy manipulation of columns.
